### PR TITLE
Make downloads more human-readable by adding thousands separators

### PR DESCRIPTION
**Pull request by hugovk**
Untested, but another attempt at https://github.com/ubershmekel/python3wos/pull/19, following tips at http://stackoverflow.com/a/31158813/724176 and http://stackoverflow.com/a/21206475/724176.

### CODE REVIEW

**Comment by hugovk** [comment]
@ubershmekel Hi, what do you think of this PR and the other two? Thank you!

**Comment by ubershmekel** [comment]
TemplateSyntaxError: Could not parse the remainder: '.format(package.downloads)' from '"{:,}".format(package.downloads)'
INFO     2017-11-16 23:43:34,420 module.py:788] default: "GET / HTTP/1.1" 500 -

**Comment by hugovk** [comment]
Hmm, what Python version do you use, and what do run to generate the output?

**Comment by hugovk** [comment]
Hmm, what Python version do you use, and what do run to generate the output?

**Comment by ubershmekel** [comment]
Per https://github.com/ubershmekel/python3wos/blob/master/app.yaml

Python 2.7

This is how I run a local copy on my windows machine: https://github.com/ubershmekel/python3wos/blob/master/host-8080.cmd

You need to download the Google App Engine tools or whatever they call them nowadays.

**Pull request merged**
